countries = {
        '0': 'Global',
        '1': 'Abruzzo',
        '2': 'Acre',
        '3': 'Adygea Republic',
        '4': 'Aguascalientes',
        '5': 'Aichi',
        '6': 'Akita',
        '7': 'Alagoas',
        '8': 'Alberta',
        '9': 'Altai Krai',
        '10': 'Altai Republic',
        '11': 'Amapa',
        '12': 'Amazonas',
        '13': 'Amazonas',
        '14': 'Amazonas',
        '15': 'Amur Oblast',
        '16': 'Ancash',
        '17': 'Andalusia',
        '18': 'Andaman and Nicobar Islands',
        '19': 'Andhra Pradesh',
        '20': 'Anguilla',
        '21': 'Anhui',
        '22': 'Antioquia',
        '23': 'Antofagasta',
        '24': 'Aomori',
        '25': 'Apurimac',
        '26': 'Aragon',
        '27': 'Arauca',
        '28': 'Araucania',
        '29': 'Arequipa',
        '30': 'Arica y Parinacota',
        '31': 'Arkhangelsk Oblast',
        '32': 'Aruba',
        '33': 'Arunachal Pradesh',
        '34': 'Assam',
        '35': 'Astrakhan Oblast',
        '36': 'Asturias',
        '37': 'Atacama',
        '38': 'Atlantico',
        '39': 'Australian Capital Territory',
        '40': 'Ayacucho',
        '41': 'Aysen',
        '42': 'Azad Jammu and Kashmir',
        '43': 'Baden-Wurttemberg',
        '44': 'Bahia',
        '45': 'Baja California',
        '46': 'Baja California Sur',
        '47': 'Baleares',
        '48': 'Balochistan',
        '49': 'Bashkortostan Republic',
        '50': 'Basilicata',
        '51': 'Bayern',
        '52': 'Beijing',
        '53': 'Belgorod Oblast',
        '54': 'Berlin',
        '55': 'Bermuda',
        '56': 'Bihar',
        '57': 'Biobio',
        '58': 'Blekinge',
        '59': 'Bolivar',
        '60': 'Bonaire, Sint Eustatius and Saba',
        '61': 'Boyaca',
        '62': 'Brandenburg',
        '63': 'Bremen',
        '64': 'British Columbia',
        '65': 'British Virgin Islands',
        '66': 'Bryansk Oblast',
        '67': 'Buryatia Republic',
        '68': 'C. Valenciana',
        '69': 'Cajamarca',
        '70': 'Calabria',
        '71': 'Caldas',
        '72': 'Callao',
        '73': 'Campania',
        '74': 'Campeche',
        '75': 'Canarias',
        '76': 'Cantabria',
        '77': 'Capital District',
        '78': 'Caqueta',
        '79': 'Casanare',
        '80': 'Castilla - La Mancha',
        '81': 'Castilla y Leon',
        '82': 'Catalonia',
        '83': 'Cauca',
        '84': 'Cayman Islands',
        '85': 'Ceara',
        '86': 'Cesar',
        '87': 'Ceuta',
        '88': 'Chandigarh',
        '89': 'Channel Islands',
        '90': 'Chechen Republic',
        '91': 'Chelyabinsk Oblast',
        '92': 'Cherkasy Oblast',
        '93': 'Chernihiv Oblast',
        '94': 'Chernivtsi Oblast',
        '95': 'Chhattisgarh',
        '96': 'Chiapas',
        '97': 'Chiba',
        '98': 'Chihuahua',
        '99': 'Choco',
        '100': 'Chongqing',
        '101': 'Chukotka Autonomous Okrug',
        '102': 'Chuvashia Republic',
        '103': 'Ciudad de Mexico',
        '104': 'Coahuila',
        '105': 'Colima',
        '106': 'Coquimbo',
        '107': 'Cordoba',
        '108': 'Crimea Republic*',
        '109': 'Cundinamarca',
        '110': 'Curacao',
        '111': 'Cusco',
        '112': 'Dadra and Nagar Haveli and Daman and Diu',
        '113': 'Dagestan Republic',
        '114': 'Dalarna',
        '115': 'Delhi',
        '116': 'Distrito Federal',
        '117': 'Dnipropetrovsk Oblast',
        '118': 'Donetsk Oblast',
        '119': 'Durango',
        '120': 'Ehime',
        '121': 'Emilia-Romagna',
        '122': 'England',
        '123': 'Espirito Santo',
        '124': 'Extremadura',
        '125': 'Falkland Islands (Malvinas)',
        '126': 'Faroe Islands',
        '127': 'French Guiana',
        '128': 'French Polynesia',
        '129': 'Friuli Venezia Giulia',
        '130': 'Fujian',
        '131': 'Fukui',
        '132': 'Fukuoka',
        '133': 'Fukushima',
        '134': 'Galicia',
        '135': 'Gansu',
        '136': 'Gavleborg',
        '137': 'Gibraltar',
        '138': 'Gifu',
        '139': 'Gilgit-Baltistan',
        '140': 'Goa',
        '141': 'Goias',
        '142': 'Gotland',
        '143': 'Greenland',
        '144': 'Guadeloupe',
        '145': 'Guainia',
        '146': 'Guam',
        '147': 'Guanajuato',
        '148': 'Guangdong',
        '149': 'Guangxi',
        '150': 'Guaviare',
        '151': 'Guerrero',
        '152': 'Guizhou',
        '153': 'Gujarat',
        '154': 'Gunma',
        '155': 'Hainan',
        '156': 'Halland',
        '157': 'Hamburg',
        '158': 'Haryana',
        '159': 'Hebei',
        '160': 'Heilongjiang',
        '161': 'Henan',
        '162': 'Hessen',
        '163': 'Hidalgo',
        '164': 'Himachal Pradesh',
        '165': 'Hiroshima',
        '166': 'Hokkaido',
        '167': 'Hong Kong',
        '168': 'Huancavelica',
        '169': 'Huanuco',
        '170': 'Hubei',
        '171': 'Huila',
        '172': 'Hunan',
        '173': 'Hyogo',
        '174': 'Ibaraki',
        '175': 'Ica',
        '176': 'Ingushetia Republic',
        '177': 'Inner Mongolia',
        '178': 'Irkutsk Oblast',
        '179': 'Ishikawa',
        '180': 'Islamabad',
        '181': 'Isle of Man',
        '182': 'Ivano-Frankivsk Oblast',
        '183': 'Ivanovo Oblast',
        '184': 'Jalisco',
        '185': 'Jammu and Kashmir',
        '186': 'Jamtland Harjedalen',
        '187': 'Jewish Autonomous Okrug',
        '188': 'Jharkhand',
        '189': 'Jiangsu',
        '190': 'Jiangxi',
        '191': 'Jilin',
        '192': 'Jonkoping',
        '193': 'Junin',
        '194': 'Kabardino-Balkarian Republic',
        '195': 'Kagawa',
        '196': 'Kagoshima',
        '197': 'Kaliningrad Oblast',
        '198': 'Kalmar',
        '199': 'Kalmykia Republic',
        '200': 'Kaluga Oblast',
        '201': 'Kamchatka Krai',
        '202': 'Kanagawa',
        '203': 'Karachay-Cherkess Republic',
        '204': 'Karelia Republic',
        '205': 'Karnataka',
        '206': 'Kemerovo Oblast',
        '207': 'Kerala',
        '208': 'Khabarovsk Krai',
        '209': 'Khakassia Republic',
        '210': 'Khanty-Mansi Autonomous Okrug',
        '211': 'Kharkiv Oblast',
        '212': 'Kherson Oblast',
        '213': 'Khmelnytskyi Oblast',
        '214': 'Khyber Pakhtunkhwa',
        '215': 'Kiev',
        '216': 'Kiev Oblast',
        '217': 'Kirov Oblast',
        '218': 'Kirovohrad Oblast',
        '219': 'Kochi',
        '220': 'Komi Republic',
        '221': 'Kostroma Oblast',
        '222': 'Krasnodar Krai',
        '223': 'Krasnoyarsk Krai',
        '224': 'Kronoberg',
        '225': 'Kumamoto',
        '226': 'Kurgan Oblast',
        '227': 'Kursk Oblast',
        '228': 'Kyoto',
        '229': 'La Guajira',
        '230': 'La Libertad',
        '231': 'La Rioja',
        '232': 'Ladakh',
        '233': 'Lambayeque',
        '234': 'Lazio',
        '235': 'Leningrad Oblast',
        '236': 'Liaoning',
        '237': 'Liguria',
        '238': 'Lima',
        '239': 'Lipetsk Oblast',
        '240': 'Lombardia',
        '241': 'Loreto',
        '242': 'Los Lagos',
        '243': 'Los Rios',
        '244': 'Luhansk Oblast',
        '245': 'Lviv Oblast',
        '246': 'Macau',
        '247': 'Madhya Pradesh',
        '248': 'Madre de Dios',
        '249': 'Madrid',
        '250': 'Magadan Oblast',
        '251': 'Magallanes',
        '252': 'Magdalena',
        '253': 'Maharashtra',
        '254': 'Manipur',
        '255': 'Manitoba',
        '256': 'Maranhao',
        '257': 'Marche',
        '258': 'Mari El Republic',
        '259': 'Martinique',
        '260': 'Mato Grosso',
        '261': 'Mato Grosso do Sul',
        '262': 'Maule',
        '263': 'Mayotte',
        '264': 'Mecklenburg-Vorpommern',
        '265': 'Meghalaya',
        '266': 'Melilla',
        '267': 'Meta',
        '268': 'Metropolitana',
        '269': 'Mexico',
        '270': 'Michoacan',
        '271': 'Mie',
        '272': 'Minas Gerais',
        '273': 'Miyagi',
        '274': 'Miyazaki',
        '275': 'Mizoram',
        '276': 'Molise',
        '277': 'Montserrat',
        '278': 'Moquegua',
        '279': 'Mordovia Republic',
        '280': 'Morelos',
        '281': 'Moscow',
        '282': 'Moscow Oblast',
        '283': 'Murcia',
        '284': 'Murmansk Oblast',
        '285': 'Mykolaiv Oblast',
        '286': 'Nagaland',
        '287': 'Nagano',
        '288': 'Nagasaki',
        '289': 'Nara',
        '290': 'Narino',
        '291': 'Navarra',
        '292': 'Nayarit',
        '293': 'Nenets Autonomous Okrug',
        '294': 'New Brunswick',
        '295': 'New Caledonia',
        '296': 'New South Wales',
        '297': 'Newfoundland and Labrador',
        '298': 'Niedersachsen',
        '299': 'Niigata',
        '300': 'Ningxia',
        '301': 'Nizhny Novgorod Oblast',
        '302': 'Nordrhein-Westfalen',
        '303': 'Norrbotten',
        '304': 'Norte de Santander',
        '305': 'North Ossetia - Alania Republic',
        '306': 'Northern Ireland',
        '307': 'Northern Mariana Islands',
        '308': 'Northern Territory',
        '309': 'Northwest Territories',
        '310': 'Nova Scotia',
        '311': 'Novgorod Oblast',
        '312': 'Novosibirsk Oblast',
        '313': 'Nuble',
        '314': 'Nuevo Leon',
        '315': 'OHiggins',
        '316': 'Oaxaca',
        '317': 'Odessa Oblast',
        '318': 'Odisha',
        '319': 'Oita',
        '320': 'Okayama',
        '321': 'Okinawa',
        '322': 'Omsk Oblast',
        '323': 'Ontario',
        '324': 'Orebro',
        '325': 'Orel Oblast',
        '326': 'Orenburg Oblast',
        '327': 'Osaka',
        '328': 'Ostergotland',
        '329': 'P.A. Bolzano',
        '330': 'P.A. Trento',
        '331': 'Pais Vasco',
        '332': 'Para',
        '333': 'Paraiba',
        '334': 'Parana',
        '335': 'Pasco',
        '336': 'Penza Oblast',
        '337': 'Perm Krai',
        '338': 'Pernambuco',
        '339': 'Piaui',
        '340': 'Piemonte',
        '341': 'Piura',
        '342': 'Poltava Oblast',
        '343': 'Primorsky Krai',
        '344': 'Prince Edward Island',
        '345': 'Pskov Oblast',
        '346': 'Puducherry',
        '347': 'Puebla',
        '348': 'Puerto Rico',
        '349': 'Puglia',
        '350': 'Punjab',
        '351': 'Punjab',
        '352': 'Puno',
        '353': 'Putumayo',
        '354': 'Qinghai',
        '355': 'Quebec',
        '356': 'Queensland',
        '357': 'Queretaro',
        '358': 'Quindio',
        '359': 'Quintana Roo',
        '360': 'Rajasthan',
        '361': 'Reunion',
        '362': 'Rheinland-Pfalz',
        '363': 'Rio Grande do Norte',
        '364': 'Rio Grande do Sul',
        '365': 'Rio de Janeiro',
        '366': 'Risaralda',
        '367': 'Rivne Oblast',
        '368': 'Rondonia',
        '369': 'Roraima',
        '370': 'Rostov Oblast',
        '371': 'Ryazan Oblast',
        '372': 'Saarland',
        '373': 'Sachsen',
        '374': 'Sachsen-Anhalt',
        '375': 'Saga',
        '376': 'Saint Barthelemy',
        '377': 'Saint Petersburg',
        '378': 'Saint Pierre and Miquelon',
        '379': 'Saitama',
        '380': 'Sakha (Yakutiya) Republic',
        '381': 'Sakhalin Oblast',
        '382': 'Samara Oblast',
        '383': 'San Andres y Providencia',
        '384': 'San Luis Potosi',
        '385': 'San Martin',
        '386': 'Santa Catarina',
        '387': 'Santander',
        '388': 'Sao Paulo',
        '389': 'Saratov Oblast',
        '390': 'Sardegna',
        '391': 'Saskatchewan',
        '392': 'Schleswig-Holstein',
        '393': 'Scotland',
        '394': 'Sergipe',
        '395': 'Sevastopol*',
        '396': 'Shaanxi',
        '397': 'Shandong',
        '398': 'Shanghai',
        '399': 'Shanxi',
        '400': 'Shiga',
        '401': 'Shimane',
        '402': 'Shizuoka',
        '403': 'Sichuan',
        '404': 'Sicilia',
        '405': 'Sikkim',
        '406': 'Sinaloa',
        '407': 'Sindh',
        '408': 'Sint Maarten',
        '409': 'Skane',
        '410': 'Smolensk Oblast',
        '411': 'Sonora',
        '412': 'Sormland',
        '413': 'South Australia',
        '414': 'St Martin',
        '415': 'Stavropol Krai',
        '416': 'Stockholm',
        '417': 'Sucre',
        '418': 'Sumy Oblast',
        '419': 'Sverdlovsk Oblast',
        '420': 'Tabasco',
        '421': 'Tacna',
        '422': 'Tamaulipas',
        '423': 'Tambov Oblast',
        '424': 'Tamil Nadu',
        '425': 'Tarapaca',
        '426': 'Tasmania',
        '427': 'Tatarstan Republic',
        '428': 'Telangana',
        '429': 'Ternopil Oblast',
        '430': 'Thuringen',
        '431': 'Tianjin',
        '432': 'Tibet',
        '433': 'Tlaxcala',
        '434': 'Tocantins',
        '435': 'Tochigi',
        '436': 'Tokushima',
        '437': 'Tokyo',
        '438': 'Tolima',
        '439': 'Tomsk Oblast',
        '440': 'Toscana',
        '441': 'Tottori',
        '442': 'Toyama',
        '443': 'Tripura',
        '444': 'Tula Oblast',
        '445': 'Tumbes',
        '446': 'Turks and Caicos Islands',
        '447': 'Tver Oblast',
        '448': 'Tyumen Oblast',
        '449': 'Tyva Republic',
        '450': 'Ucayali',
        '451': 'Udmurt Republic',
        '452': 'Ulyanovsk Oblast',
        '453': 'Umbria',
        '454': 'Uppsala',
        '455': 'Uttar Pradesh',
        '456': 'Uttarakhand',
        '457': "Valle d'Aosta",
        '458': 'Valle del Cauca',
        '459': 'Valparaiso',
        '460': 'Varmland',
        '461': 'Vasterbotten',
        '462': 'Vasternorrland',
        '463': 'Vastmanland',
        '464': 'Vastra Gotaland',
        '465': 'Vaupes',
        '466': 'Veneto',
        '467': 'Veracruz',
        '468': 'Vichada',
        '469': 'Victoria',
        '470': 'Vinnytsia Oblast',
        '471': 'Virgin Islands',
        '472': 'Vladimir Oblast',
        '473': 'Volgograd Oblast',
        '474': 'Vologda Oblast',
        '475': 'Volyn Oblast',
        '476': 'Voronezh Oblast',
        '477': 'Wakayama',
        '478': 'Wales',
        '479': 'West Bengal',
        '480': 'Western Australia',
        '481': 'Xinjiang',
        '482': 'Yamagata',
        '483': 'Yamaguchi',
        '484': 'Yamalo-Nenets Autonomous Okrug',
        '485': 'Yamanashi',
        '486': 'Yaroslavl Oblast',
        '487': 'Yucatan',
        '488': 'Yukon',
        '489': 'Yunnan',
        '490': 'Zabaykalsky Krai',
        '491': 'Zacatecas',
        '492': 'Zakarpattia Oblast',
        '493': 'Zaporizhia Oblast',
        '494': 'Zhejiang',
        '495': 'Zhytomyr Oblast',
        '496': 'Afghanistan',
        '497': 'Albania',
        '498': 'Algeria',
        '499': 'Andorra',
        '500': 'Angola',
        '501': 'Antigua and Barbuda',
        '502': 'Argentina',
        '503': 'Armenia',
        '504': 'Austria',
        '505': 'Azerbaijan',
        '506': 'Bahamas',
        '507': 'Bahrain',
        '508': 'Bangladesh',
        '509': 'Barbados',
        '510': 'Belarus',
        '511': 'Belgium',
        '512': 'Belize',
        '513': 'Benin',
        '514': 'Bhutan',
        '515': 'Bolivia',
        '516': 'Bosnia and Herzegovina',
        '517': 'Botswana',
        '518': 'Brunei',
        '519': 'Bulgaria',
        '520': 'Burkina Faso',
        '521': 'Burma',
        '522': 'Burundi',
        '523': 'Cabo Verde',
        '524': 'Cambodia',
        '525': 'Cameroon',
        '526': 'Central African Republic',
        '527': 'Chad',
        '528': 'Comoros',
        '529': 'Congo (Brazzaville)',
        '530': 'Congo (Kinshasa)',
        '531': 'Costa Rica',
        '532': "Cote d'Ivoire",
        '533': 'Croatia',
        '534': 'Cuba',
        '535': 'Cyprus',
        '536': 'Czechia',
        '537': 'Denmark',
        '538': 'Djibouti',
        '539': 'Dominica',
        '540': 'Dominican Republic',
        '541': 'Ecuador',
        '542': 'Egypt',
        '543': 'El Salvador',
        '544': 'Equatorial Guinea',
        '545': 'Eritrea',
        '546': 'Estonia',
        '547': 'Eswatini',
        '548': 'Ethiopia',
        '549': 'Fiji',
        '550': 'Finland',
        '551': 'France',
        '552': 'Gabon',
        '553': 'Gambia',
        '554': 'Georgia',
        '555': 'Ghana',
        '556': 'Greece',
        '557': 'Grenada',
        '558': 'Guatemala',
        '559': 'Guinea',
        '560': 'Guinea-Bissau',
        '561': 'Guyana',
        '562': 'Haiti',
        '563': 'Holy See',
        '564': 'Honduras',
        '565': 'Hungary',
        '566': 'Iceland',
        '567': 'Indonesia',
        '568': 'Iran',
        '569': 'Iraq',
        '570': 'Ireland',
        '571': 'Israel',
        '572': 'Jamaica',
        '573': 'Jordan',
        '574': 'Kazakhstan',
        '575': 'Kenya',
        '576': 'Korea, South',
        '577': 'Kosovo',
        '578': 'Kuwait',
        '579': 'Kyrgyzstan',
        '580': 'Laos',
        '581': 'Latvia',
        '582': 'Lebanon',
        '583': 'Lesotho',
        '584': 'Liberia',
        '585': 'Libya',
        '586': 'Liechtenstein',
        '587': 'Lithuania',
        '588': 'Luxembourg',
        '589': 'Madagascar',
        '590': 'Malawi',
        '591': 'Malaysia',
        '592': 'Maldives',
        '593': 'Mali',
        '594': 'Malta',
        '595': 'Mauritania',
        '596': 'Mauritius',
        '597': 'Moldova',
        '598': 'Monaco',
        '599': 'Mongolia',
        '600': 'Montenegro',
        '601': 'Morocco',
        '602': 'Mozambique',
        '603': 'Namibia',
        '604': 'Nepal',
        '605': 'Netherlands',
        '606': 'New Zealand',
        '607': 'Nicaragua',
        '608': 'Niger',
        '609': 'Nigeria',
        '610': 'North Macedonia',
        '611': 'Norway',
        '612': 'Oman',
        '613': 'Panama',
        '614': 'Papua New Guinea',
        '615': 'Paraguay',
        '616': 'Philippines',
        '617': 'Poland',
        '618': 'Portugal',
        '619': 'Qatar',
        '620': 'Romania',
        '621': 'Rwanda',
        '622': 'Saint Kitts and Nevis',
        '623': 'Saint Lucia',
        '624': 'Saint Vincent and the Grenadines',
        '625': 'San Marino',
        '626': 'Sao Tome and Principe',
        '627': 'Saudi Arabia',
        '628': 'Senegal',
        '629': 'Serbia',
        '630': 'Seychelles',
        '631': 'Sierra Leone',
        '632': 'Singapore',
        '633': 'Slovakia',
        '634': 'Slovenia',
        '635': 'Somalia',
        '636': 'South Africa',
        '637': 'South Sudan',
        '638': 'Sri Lanka',
        '639': 'Sudan',
        '640': 'Suriname',
        '641': 'Switzerland',
        '642': 'Syria',
        '643': 'Taiwan*',
        '644': 'Tajikistan',
        '645': 'Tanzania',
        '646': 'Thailand',
        '647': 'Timor-Leste',
        '648': 'Togo',
        '649': 'Trinidad and Tobago',
        '650': 'Tunisia',
        '651': 'Turkey',
        '652': 'Uganda',
        '653': 'United Arab Emirates',
        '654': 'Uruguay',
        '655': 'Uzbekistan',
        '656': 'Venezuela',
        '657': 'Vietnam',
        '658': 'West Bank and Gaza',
        '659': 'Western Sahara',
        '660': 'Yemen',
        '661': 'Zambia',
        '662': 'Zimbabwe',
        '663': 'South Carolina',
        '664': 'Louisiana',
        '665': 'Virginia',
        '666': 'Idaho',
        '667': 'Iowa',
        '668': 'Kentucky',
        '669': 'Missouri',
        '670': 'Oklahoma',
        '671': 'Colorado',
        '672': 'Illinois',
        '673': 'Indiana',
        '674': 'Mississippi',
        '675': 'Nebraska',
        '676': 'Ohio',
        '677': 'Pennsylvania',
        '678': 'Washington',
        '679': 'Wisconsin',
        '680': 'Vermont',
        '681': 'Minnesota',
        '682': 'Florida',
        '683': 'North Carolina',
        '684': 'California',
        '685': 'New York',
        '686': 'Wyoming',
        '687': 'Michigan',
        '688': 'Maryland',
        '689': 'Kansas',
        '690': 'Alaska',
        '691': 'Tennessee',
        '692': 'Texas',
        '693': 'Maine',
        '694': 'Arizona',
        '695': 'Georgia',
        '696': 'Arkansas',
        '697': 'New Jersey',
        '698': 'South Dakota',
        '699': 'Alabama',
        '700': 'Oregon',
        '701': 'West Virginia',
        '702': 'North Dakota',
        '703': 'Massachusetts',
        '704': 'Utah',
        '705': 'Montana',
        '706': 'New Hampshire',
        '707': 'New Mexico',
        '708': 'Rhode Island',
        '709': 'Nevada',
        '710': 'District of Columbia',
        '711': 'Connecticut',
        '712': 'Hawaii',
        '713': 'Delaware'
}

countries_options = [
    {"label": str(countries[c]), "value": str(c)}
    for c in countries
]

states = [
  "american samoa",
  "guam",
  "northern mariana islands",
  "puerto rico",
  "virgin islands",
  "alabama",
  "alaska",
  "arizona",
  "arkansas",
  "california",
  "colorado",
  "connecticut",
  "delaware",
  "district of columbia",
  "florida",
  "georgia",
  "hawaii",
  "idaho",
  "illinois",
  "indiana",
  "iowa",
  "kansas",
  "kentucky",
  "louisiana",
  "maine",
  "maryland",
  "massachusetts",
  "michigan",
  "minnesota",
  "mississippi",
  "missouri",
  "montana",
  "nebraska",
  "nevada",
  "new hampshire",
  "new jersey",
  "new mexico",
  "new york",
  "north carolina",
  "north dakota",
  "ohio",
  "oklahoma",
  "oregon",
  "pennsylvania",
  "rhode island",
  "south carolina",
  "south dakota",
  "tennessee",
  "texas",
  "utah",
  "vermont",
  "virginia",
  "washington",
  "west virginia",
  "wisconsin",
  "wyoming"]
